Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant"
  
  config.vm.define "mukelesS" do |master|
    master.vm.box = "generic/alpine319"
    master.vm.hostname = "mukelesS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |v|
      v.name = "mukelesS"
      v.memory = 1024
      v.cpus = 1
    end
    master.vm.provision "shell", path: "scripts/server.sh"
  end
  
  config.vm.define "mukelesSW" do |agent|
    agent.vm.box = "generic/alpine319"
    agent.vm.hostname = "mukelesSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "virtualbox" do |v|
      v.name = "mukelesSW"
      v.memory = 1024
      v.cpus = 1
    end
    agent.vm.provision "shell", path: "scripts/worker.sh"
  end
end
