Vagrant.configure("2") do |configuration|

  configuration.vm.synced_folder ".", "/vagrant"

  configuration.vm.define "mukeles" do |master_node|
    master_node.vm.box = "generic/alpine319"
    master_node.vm.hostname = "mukeles"
    master_node.vm.network "private_network", ip: "192.168.56.110"
    master_node.vm.provider "virtualbox" do |vm_provider|
      vm_provider.name = "mukeles"
      vm_provider.memory = 1024
      vm_provider.cpus = 1
    end
    master_node.vm.provision "shell", path: "scripts/server.sh"
  end
  
  configuration.vm.define "mukelesW" do |worker_node|
    worker_node.vm.box = "generic/alpine319"
    worker_node.vm.hostname = "mukelesW"
    worker_node.vm.network "private_network", ip: "192.168.56.111"
    worker_node.vm.provider "virtualbox" do |vm_provider|
      vm_provider.name = "mukelesW"
      vm_provider.memory = 1024
      vm_provider.cpus = 1
    end
    worker_node.vm.provision "shell", path: "scripts/worker.sh"
  end
end
