Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = true
  config.vm.boot_timeout = 600

  config.vm.define "eozmert" do |vm|
    vm.vm.hostname = "eozmertS"

    # Port forwarding
    vm.vm.network "forwarded_port", guest: 8888, host: 8888
    vm.vm.network "forwarded_port", guest: 8080, host: 8080

    vm.vm.provider "virtualbox" do |vb|
      vb.name = "eozmertS"
      vb.cpus = 1
      vb.memory = 1024
      vb.gui = false
    end

    vm.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    vm.vm.provision "shell", path: "scripts/install.sh"
    vm.vm.provision :reload
    vm.vm.provision "shell", path: "scripts/setup.sh", privileged: false
  end
end